// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://gcrrgedjgapvrahmultn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdjcnJnZWRqZ2FwdnJhaG11bHRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIwNTA2ODEsImV4cCI6MjA4NzYyNjY4MX0.xOXdbAcG_nP8iXjLocvlmKQ1lCXirBUEJMkScF15sjk";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);